resources:
  - ../../base

images:
  - name: ghcr.io/slaca93/interview-demo-backend
    newTag: latest
  - name: ghcr.io/slaca93/interview-demo-frontend
    newTag: latest

patches:
  - path: backend-deployment.yaml
  - path: frontend-deployment.yaml